### ISSUE TITLE
是否可以提供docker版，谢谢

### ISSUE THREAD

**Issue by JasonLawd** [muhanstudio/siyuan-sync-aware-serve#1]

**Comment by muhanstudio** [comment]
这个项目核心只有一个nodejs程序文件，专门封装一个docker镜像感觉有一点小题大做了

**Comment by kentbryan404** [comment]
感谢作者大大，已成构建镜像！！！

```
git clone https://github.com/muhanstudio/siyuan-sync-aware-serve.git
cd siyuan-sync-aware-serve
cat >> Dockerfile << "EOF"
# 使用官方 Node.js 镜像作为基础镜像
FROM node:14
# 指定工作目录
WORKDIR /app
# 复制文件
COPY package*.json ./
# 安装依赖
RUN npm install
# 复制项目文件到容器中
COPY aware.js ./
COPY data.json ./
# 暴露应用运行的端口
EXPOSE 80
# 命令行启动应用
CMD ["node", "aware.js"]
EOF
docker build -t siyuan-sync .
docker run -itd --name=siyuan-sync -p 28888:80 siyuan-sync
docker ps -a
```

**Comment by muhanstudio** [comment]
> 感谢作者大大，已成构建镜像！！！
> 
> ```
> git clone https://github.com/muhanstudio/siyuan-sync-aware-serve.git
> cd siyuan-sync-aware-serve
> cat >> Dockerfile << "EOF"
> # 使用官方 Node.js 镜像作为基础镜像
> FROM node:14
> # 指定工作目录
> WORKDIR /app
> # 复制文件
> COPY package*.json ./
> # 安装依赖
> RUN npm install
> # 复制项目文件到容器中
> COPY aware.js ./
> COPY data.json ./
> # 暴露应用运行的端口
> EXPOSE 80
> # 命令行启动应用
> CMD ["node", "aware.js"]
> EOF
> docker build -t siyuan-sync .
> docker run -itd --name=siyuan-sync -p 28888:80 siyuan-sync
> docker ps -a
> ```

🐂的，可以上传到docker仓库给大家分享一下

**Comment by kentbryan404** [comment]
这个是已经封装好的镜像，已经上传到公共镜像仓库，各位友友可以直接使用！！！
docker pull ccr.ccs.tencentyun.com/kentstationcloud/siyuan-sync:latest

**Comment by lzren8** [comment]
大佬开个github项目啊，我跟着更新
