### ISSUE TITLE
感知到变化后没有及时上传

### ISSUE THREAD

**Issue by mixyoung** [muhanstudio/siyuan-sync-aware-serve#2]
![图片](https://github.com/user-attachments/assets/833cc567-a2bd-4556-abdd-76d3d9a8de1b)
已经搭建成功了，谢谢。其他想了解一下插件动作流程。
我看本地状态栏不停显示在提交索引，但是没有像其他在线笔记一样另外一端直接同步出内容，就算感知到动作后也等了很久才进行同步。还是可能出现同步锁定，而且同步的变化没有及时体现。

**Comment by muhanstudio** [comment]
> ![图片](https://private-user-images.githubusercontent.com/4831835/369856747-833cc567-a2bd-4556-abdd-76d3d9a8de1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTM5OTksIm5iZiI6MTcyODk1MzY5OSwicGF0aCI6Ii80ODMxODM1LzM2OTg1Njc0Ny04MzNjYzU2Ny1hMmJkLTQ1NTYtYWJkZC03NmQzZDlhOGRlMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDA1NDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I0YTg4ZWQ0NGYyMTFhNDZiNmI1YzRiZjQ2NjFmNjRhYWJjOGVkMWY5NDEwODY4MGU0NGFmMzI0ZTU0MzMwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XPOZMrlX3uJ3EMX23e9xC7_mvTAlgX8vJyIE8ODSoTU) 已经搭建成功了，谢谢。其他想了解一下插件动作流程。 我看本地状态栏不停显示在提交索引，但是没有像其他在线笔记一样另外一端直接同步出内容，就算感知到动作后也等了很久才进行同步。还是可能出现同步锁定，而且同步的变化没有及时体现。

这个插件是监听本地文件变化，然后fetch思源发起同步的api来通知思源进行同步的，并不是一个第三方同步方式，本质上是自动提醒思源开始同步
